---
- name: provision system dependencies & users, perform basic hardening
  become: true
  hosts: nextcloud

  handlers:
    - name: restart fail2ban
      service: name=fail2ban state=restarted

    - name: restart ssh
      service: name=ssh state=restarted

    - name: reload ufw
      ufw:
        state: reloaded

  tasks:

  #######################
  # SYSTEM DEPENDENCIES #
  #######################

  - name: update apt packages
    apt:
      update_cache: yes
      cache_valid_time: 3600
    tags: packages

  - name: upgrade apt packages
    apt: upgrade=yes
    tags: packages

  - name: Install basic packages
    apt:
      cache_valid_time: 3600
      name:
        - sudo
        - curl
        - gnupg
        - fail2ban
        - ufw
        - tmux
        - git
        - htop
        - lsof
        - rsync
        - python3
        - emacs-nox
    tags: packages

  ##########
  # ADMINS #
  ##########

  - name: Make sure we have a sshusers groups
    group:
      name: sshusers
      state: present

  - name: Add admin users
    user:
      name: "{{ item.name }}"
      groups:
        - sudo
        - sshusers
      append: yes
      shell: /bin/bash
    with_items: "{{ admins }}"

  - name: Set authorized keys
    authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "{{ item.ssh_key }}"
    with_items: "{{ admins }}"

  - name: Allow sudo group to have passwordless sudo
    lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

  #############
  # HARDENING #
  #############

  # ssh

  - name: ssh hardening
    import_role:
      name: dev-sec.ssh-hardening
    vars:
      ssh_allow_groups: sshusers

  - name: unlock admin users
    become: yes
    command: "usermod -p '*' {{ item.name }}"
    ignore_errors: True
    changed_when: False
    loop: "{{ admins }}"

  # firewall

  - ufw: state=enabled policy=allow
    tags: ufw

  - name: default (incoming) policy
    ufw:
      policy: deny
      direction: incoming
    notify: reload ufw
    tags: ufw

  - name: default (outgoing) policy
    ufw:
      policy: allow
      direction: outgoing
    notify: reload ufw
    tags: ufw

  - name: limit ssh
    ufw:
      rule: limit
      port: ssh
      proto: tcp
    notify: reload ufw
    tags: ufw

  # fail2ban

  - name: Copy fail2ban configuration into place
    become: true
    copy:
      src: "files/jail.local"
      dest: /etc/fail2ban/jail.local
    notify: restart fail2ban

  - name: Ensure fail2ban is started
    service: name=fail2ban state=started
